from bot import main


# {
#    "first_name":"MLS Agent Name",
#    "last_name":"MLS Agent Name",
#    "phone_number":"MLS Agent Phone",
#    "email":"MLS Agent E-Mail",
#    "Property Address":"Address",
#    "Property City":"City",
#    "Property State":"State",
#    "Property Zip":"Zip",
#    "Property County":"County",
#    "APN":"APN",
#    "MLS Agent E-Mail":"MLS Agent E-Mail",
#    "Owner 1 First Name":"Owner 1 First Name",
#    "Owner 1 Last Name":"Owner 1 Last Name",
#    "Owner 2 First Name":"Owner 2 First Name",
#    "Owner 2 Last Name":"Owner 2 Last Name",
#    "Property Type":"Property Type",
#    "Bedrooms":"Bedrooms",
#    "Total Bathrooms":"Total Bathrooms",
#    "Building Sqft":"Building Sqft",
#    "Lot Size Sqft":"Lot Size Sqft",
#    "Year Built":"Year Built",
#    "Is there an HOA?":"HOA Present",
#    "Stories":"Number of Stories",
#    "Loan 1 Balance":"Loan 1 Balance",
#    "Loan 1 Rate":"Loan 1 Rate",
#    "Loan 1 Rate Type":"Loan 1 Rate Type",
#    "Loan 2 Balance":"Loan 2 Balance",
#    "Loan 2 Type":"Loan 2 Type",
#    "Loan 2 Rate":"Loan 2 Rate",
#    "Loan 2 Rate Type":"Loan 2 Rate Type",
#    "Condition":"Total Condition",
#    "Listing Status":"MLS Status",
#    "MLS Amount":"MLS Amount",
#    "MLS Agent Name":"MLS Agent Name",
#    "MLS Agent Phone":"MLS Agent Phone",
#    "MLS Brokerage Name":"MLS Brokerage Name",
#    "MLS Brokerage Phone":"MLS Brokerage Phone"
# }
